site:
  name: 'CSI - Innowave'
  site: 'https://csi-innowave.vercel.app'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: 'CSI - Innowave | Technocultural Society of MAIT'
    template: '%s â€” CSI - Innowave'
  description: "The Computer Society of India chapter at MAIT - Where Innovation Meets Excellence. Explore tech events, workshops, and student-driven innovation since 2009."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'CSI - Innowave'
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@csi_innowave'
    site: '@csi_innowave'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 9

    post:
      isEnabled: true
      permalink: '/events/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'events' # Events main path
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
